
package com.borabora.wsupandrunning.ch05.wss.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EchoServiceImplService", targetNamespace = "http://wss.ch05.wsupandrunning.borabora.com/", wsdlLocation = "http://localhost:7777/echo?wsdl")
public class EchoServiceImplService
    extends Service
{

    private final static URL ECHOSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.borabora.wsupandrunning.ch05.wss.client.EchoServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.borabora.wsupandrunning.ch05.wss.client.EchoServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:7777/echo?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:7777/echo?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ECHOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public EchoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EchoServiceImplService() {
        super(ECHOSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://wss.ch05.wsupandrunning.borabora.com/", "EchoServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns EchoServiceImpl
     */
    @WebEndpoint(name = "EchoServiceImplPort")
    public EchoServiceImpl getEchoServiceImplPort() {
        return super.getPort(new QName("http://wss.ch05.wsupandrunning.borabora.com/", "EchoServiceImplPort"), EchoServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EchoServiceImpl
     */
    @WebEndpoint(name = "EchoServiceImplPort")
    public EchoServiceImpl getEchoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wss.ch05.wsupandrunning.borabora.com/", "EchoServiceImplPort"), EchoServiceImpl.class, features);
    }

}
