
package com.borabora.wsupandrunning.ch05.wss.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EchoServiceImpl", targetNamespace = "http://wss.ch05.wsupandrunning.borabora.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EchoServiceImpl {


    /**
     * 
     * @param parameters
     * @return
     *     returns EchoMethodResponse
     */
    @WebMethod
    @WebResult(name = "echoMethodResponse", targetNamespace = "http://wss.ch05.wsupandrunning.borabora.com/", partName = "parameters")
    public EchoMethodResponse echoMethod(
        @WebParam(name = "echoMethod", targetNamespace = "http://wss.ch05.wsupandrunning.borabora.com/", partName = "parameters")
        EchoMethod parameters);

}
